name: jonggack_topik
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  get: ^4.6.5
  flutter_svg: ^1.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animate_do: ^3.0.2
  flutter_slidable: ^4.0.0
  flutter_animation_progress_bar: ^2.3.1
  # file_picker: ^9.0.1
  flutter_tts: ^4.2.3
  table_calendar: ^3.0.9
  # excel: ^2.0.4
  # tutorial_coach_mark: ^1.2.8

  # url_launcher: ^6.1.11
  change_app_package_name: ^1.1.0
  # flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  device_info_plus: ^9.1.2
  in_app_review: ^2.0.9
  flutter_widget_from_html_core: ^0.15.2
  confetti: ^0.7.0
  auto_size_text: ^3.0.0
  flutter_email_sender: ^7.0.0
  # toggle_switch: ^2.3.0
  intl: ^0.20.2
  persistent_bottom_nav_bar: ^6.2.1
  flutter_debouncer: ^2.0.0
  logger: ^2.5.0
  dropdown_button2: ^2.3.9
  fl_chart: ^1.0.0
  # permission_handler: ^12.0.0+1
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  timezone: ^0.9.4
  percent_indicator: ^4.2.5
  google_mobile_ads: ^6.0.0
  package_info_plus: ^8.3.0
  in_app_purchase: ^3.2.3
  # flutter_native_timezone: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/data/
    - assets/images/
    - assets/sounds/speech_to_text_cancel.m4r
    - assets/sounds/speech_to_text_listening.m4r
    - assets/sounds/speech_to_text_stop.m4r

  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
          weight: 100
        - asset: assets/fonts/NanumGothic-Regular.ttf
          weight: 200
        - asset: assets/fonts/NanumGothic-Regular.ttf
          weight: 300
        - asset: assets/fonts/NanumGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 500
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 600
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NanumGothic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NanumGothic-ExtraBold.ttf
          weight: 900

    # - family: NotoSerifJP
    #   fonts:
    #     - asset: assets/fonts/NotoSerifJP-ExtraLight.otf
    #       weight: 200
    #     - asset: assets/fonts/NotoSerifJP-Light.otf
    #       weight: 300
    #     - asset: assets/fonts/NotoSerifJP-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/NotoSerifJP-Medium.otf
    #       weight: 500
    #     - asset: assets/fonts/NotoSerifJP-SemiBold.otf
    #       weight: 700
    #     - asset: assets/fonts/NotoSerifJP-Bold.otf
    #       weight: 800
    #     - asset: assets/fonts/NotoSerifJP-Black.otf
    #       weight: 900

    # - family: ScoreStd
    #   fonts:
    #     - asset: assets/fonts/Montserrat-Thin.ttf
    #       weight: 100
    #     - asset: assets/fonts/Montserrat-ExtraLight.ttf
    #       weight: 200
    #     - asset: assets/fonts/Montserrat-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/Caveat-Regular.ttf
    #       weight: 400
    #     - asset: assets/fonts/Caveat-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Caveat-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Caveat-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/Montserrat-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/Montserrat-Black.ttf
    #       weight: 900
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700

    - family: GMarket
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
          weight: 300
        - asset: assets/fonts/GmarketSansTTFLight.ttf
          weight: 500
        - asset: assets/fonts/GmarketSansTTFBold.ttf
          weight: 700

    # aa

    - family: ZenMaruGothic
      fonts:
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Light.ttf
          weight: 200
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 600
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Black.ttf
          weight: 900

    - family: CookieRunFont
      fonts:
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Regular.ttf
          weight: 100
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Regular.ttf
          weight: 200
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Regular.ttf
          weight: 300
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Regular.ttf
          weight: 400
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Bold.ttf
          weight: 500
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Bold.ttf
          weight: 600
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Bold.ttf
          weight: 700
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Black.ttf
          weight: 800
        - asset: assets/fonts/CookieRunFont_TTF/CookieRun-Black.ttf
          weight: 900
